import 'package:flutter/material.dart';
import 'package:flutter_app/widgets/security_model.dart';
import 'package:flutter_app/widgets/security_model.dart';
import 'package:flutter_app/widgets/security_xml.dart';
import 'package:syncfusion_flutter_charts/charts.dart';
import 'package:syncfusion_flutter_charts/sparkcharts.dart';
class ChartApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    // FetchData().data();
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: _MyHomePage(),
    );
  }
}

class _MyHomePage extends StatefulWidget {
  // ignore: prefer_const_constructors_in_immutables
  _MyHomePage({Key? key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<_MyHomePage> {
  List<_SalesData> data = [
    _SalesData('Jan', 35),
    _SalesData('Feb', 28),
    _SalesData('Mar', 34),
    _SalesData('Apr', 32),
    _SalesData('May', 40)
  ];
  // var securityies=Security().fetchSecurity();
  // var securityies=[
  //   Security(hebName: "אלטשולר שחם י 20-80", key: "5114236", FUNDSClass: 135,FundBondPortfolioDurationTotal:0.314,FundBondPortfolioDurDomGovShikli:0.11 ),
  //   Security(hebName: "אלטשולר שחם י 20-80", key: "5114236", FUNDSClass: 135,FundBondPortfolioDurationTotal:0.314,FundBondPortfolioDurDomGovShikli:0.11 ),
  //   Security(hebName: "אלטשולר שחם י 20-80", key: "5114236", FUNDSClass: 135,FundBondPortfolioDurationTotal:0.314,FundBondPortfolioDurDomGovShikli:0.11 ),
  //   Security(hebName: "אלטשולר שחם י 20-80", key: "5114236", FUNDSClass: 135,FundBondPortfolioDurationTotal:0.314,FundBondPortfolioDurDomGovShikli:0.11 ),
  // ];
  @override
  Widget build(BuildContext context) {
    // late Future<Autogenerated> autogenerated;
    // autogenerated=Autogenerated().fetchAlbum();
    return Scaffold(
        body: Center(
            child: Container(
              padding: EdgeInsets.only(left: 20,right: 20),
                child: SfSparkLineChart(
                  //Enable the trackball
                  trackball: SparkChartTrackball(
                      activationMode: SparkChartActivationMode.tap),
                  //Enable marker
                  marker: SparkChartMarker(
                      displayMode: SparkChartMarkerDisplayMode.all),
                  //Enable data label
                  labelDisplayMode: SparkChartLabelDisplayMode.all,
                  data: <double>[
                    0.5, 0.6, 0.9,
                  ],
                )
            )
        )
    );
  }
}

class _SalesData {
  _SalesData(this.year, this.sales);

  final String year;
  final double sales;
}
