
import 'dart:convert';
import 'package:http/http.dart' as http;

class Autogenerated {

  Future<Autogenerated> fetchAutogenerated() async {
    final response = await http
        .get(Uri.parse('https://aio.tradeone.co.il:29006/v2/json2/market/table/simple?population=PKEY_FND&fields=HebName,FUNDSSuperClass,FundBondPortfolioDurDomGovShikli,FundBondPortfolioDurationTotal'));

    if (response.statusCode == 200) {
      Autogenerated autogenerated=Autogenerated.fromJson(jsonDecode(response.body));

      return Autogenerated.fromJson(jsonDecode(response.body));
    } else {
      throw Exception('Failed to load album');
    }
  }
  Table? table;

  Autogenerated({this.table});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    table = json['Table'] != null ? new Table.fromJson(json['Table']) : null;
  }
}

class Table {
  String? asOfDate;
  List<Security>? security;

  Table({this.asOfDate, this.security});

  Table.fromJson(Map<String, dynamic> json) {
    asOfDate = json['-AsOfDate'];
    if (json['Security'] != null) {
      security = <Security>[];
      json['Security'].forEach((v) {
        security!.add(new Security.fromJson(v));
      });
    }
  }

}

class Security {
  String? key;
  String? hebName;
  String? fUNDSSuperClass;
  double? fundBondPortfolioDurDomGovShikli;
  double? fundBondPortfolioDurationTotal;

  Security(
      {this.key,
        this.hebName,
        this.fUNDSSuperClass,
        this.fundBondPortfolioDurDomGovShikli,
        this.fundBondPortfolioDurationTotal});

  Security.fromJson(Map<String, dynamic> json) {
    key = json['-Key'];
    hebName = json['HebName'];
    fUNDSSuperClass = json['FUNDSSuperClass'];
    fundBondPortfolioDurDomGovShikli = json['FundBondPortfolioDurDomGovShikli'];
    fundBondPortfolioDurationTotal = json['FundBondPortfolioDurationTotal'];
  }

}


